# Generated by Django 5.1.7 on 2025-03-19 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('liqpay', 'LiqPay'), ('googlepay', 'Google Pay')], default='cash', max_length=50)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовивіз'), ('courier', "Кур'єр"), ('nova_poshta', 'Нова Пошта')], default='pickup', max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'Обробка'), ('paid', 'Оплачене'), ('shipped', 'Відправлене')], default='new', max_length=20)),
                ('call_me', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
