# Generated by Django 5.1.6 on 2025-04-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_final_price_order_selected_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_discount',
        ),
    ]
