# Generated by Django 5.1.6 on 2025-05-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_alter_birthdaydiscount_options_and_more'),
        ('order', '0012_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='birthday_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.birthdaydiscount'),
        ),
    ]
