# Generated by Django 5.1.6 on 2025-05-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_alter_birthdaydiscount_options_and_more'),
        ('order', '0013_order_birthday_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.coupon'),
        ),
    ]
