# Generated by Django 5.1.6 on 2025-05-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_coupon'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('in_transit', 'In Transit'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('in_transit', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='order.order')),
                ('warehouse_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousestock')),
            ],
            options={
                'unique_together': {('order', 'warehouse_stock')},
            },
        ),
    ]
