exclude: '^$'
fail_fast: true
repos:
  # Local hook for ruff (uses version from requirements.txt / pyproject.toml)
  - repo: local
    hooks:
      - id: ruff_lint
        name: ruff (lint)
        entry: ruff check --target-version py311
        language: system
        types: [python]
        files: "^project_1444/.*\\.py$"

      - id: ruff_format
        name: ruff (format)
        entry: ruff format --target-version py311
        language: system
        types: [ python ]
        files: "^project_1444/.*\\.py$"

#      - id: black
#        name: black (format)
#        entry: black
#        language: system
#        types: [python]
#        files: "^project_1444/.*\\.py$"


      - id: spectacular-openapi
        name: generate openapi.yaml
        entry: python scripts/generate_openapi.py
        language: system
        pass_filenames: false
        files: "project_1444/.*(urls|views|serializers|api)\\.py$"

