# Generated by Django 5.1.6 on 2025-03-03 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Ліміт використання')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
