# Generated by Django 5.1.7 on 2025-03-17 18:11

import discounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Персональна знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стара ціна')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нова ціна')),
                ('discount_applied', models.CharField(blank=True, max_length=255, null=True, verbose_name='Застосована знижка')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=discounts.models.generate_promo_code, max_length=20, unique=True, verbose_name='Промокод')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Ліміт використання')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Знижка на день народження, %')),
                ('valid_days', models.PositiveIntegerField(default=7, verbose_name='Дійсна кількість днів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_discount', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
