# Generated by Django 5.1.7 on 2025-03-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('discounts', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldiscount',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='personal_discounts', to='product.categories', verbose_name='Застосовується до категорій'),
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='personal_discounts', to='product.product', verbose_name='Застосовується до товарів'),
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Призначив'),
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='group_discounts', to='auth.group', verbose_name='Групи користувачів'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='product.categories', verbose_name='Застосовується до категорій'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='product.product', verbose_name='Застосовується до товарів'),
        ),
    ]
