# Generated by Django 5.1.6 on 2025-03-03 14:02

import discounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('product', '0014_remove_product_gender_product_subcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='product.categories', verbose_name='Застосовується до категорій'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='product.product', verbose_name='Застосовується до товарів'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=discounts.models.generate_promo_code, max_length=20, unique=True, verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='BirthdayDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Знижка на день народження, %')),
                ('valid_days', models.PositiveIntegerField(default=7, verbose_name='Дійсна кількість днів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_discount', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Персональна знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='personal_discounts', to='product.categories', verbose_name='Застосовується до категорій')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='personal_discounts', to='product.product', verbose_name='Застосовується до товарів')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Призначив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стара ціна')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нова ціна')),
                ('discount_applied', models.CharField(blank=True, max_length=255, null=True, verbose_name='Застосована знижка')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
