# Generated by Django 5.1.6 on 2025-03-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('discounts', '0002_promocode_applicable_categories_and_more'),
        ('product', '0014_remove_product_gender_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldiscount',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='group_discounts', to='auth.group', verbose_name='Групи користувачів'),
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
