# Generated by Django 5.1.6 on 2025-04-07 05:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_bonusaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс бонусів'),
        ),
    ]
