# Generated by Django 5.1.6 on 2025-04-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_bonusaccount_balance'),
        ('product', '0028_alter_productcertificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='product.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_discounts', to='product.categories', verbose_name='Категорії')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_discounts', to='product.product', verbose_name='Колекції')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GemstoneDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemstone_discounts', to='product.productgemstone', verbose_name='Каміння')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_discounts', to='product.productmaterial', verbose_name='Матеріал')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccasionsDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('ocassions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions_discounts', to='product.product', verbose_name='Привід')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_discounts', to='product.product', verbose_name='Статус')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StylesDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles_discounts', to='product.productattributes', verbose_name='Стилі')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Початок дії')),
                ('valid_to', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_discounts', to='product.subproducts', verbose_name='Підкатегорії')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
