# Generated by Django 5.1.6 on 2025-04-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_productdiscount_product_categorydiscount_and_more'),
        ('product', '0028_alter_productcertificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdiscount',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_discounts', to='product.material', verbose_name='Матеріал'),
        ),
    ]
