# Generated by Django 5.1.6 on 2025-04-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_alter_materialdiscount_material'),
        ('product', '0028_alter_productcertificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdiscount',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_discounts', to='product.productstatus', verbose_name='Статус'),
        ),
    ]
