# Generated by Django 5.1.6 on 2025-04-11 08:04
from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import make_aware


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0007_alter_statusdiscount_status"),
        ("order", "0004_alter_order_user"),
        ("product", "0028_alter_productcertificate_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectiondiscount",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="gemstonediscount",
            name="gemstone",
        ),
        migrations.RemoveField(
            model_name="materialdiscount",
            name="material",
        ),
        migrations.RemoveField(
            model_name="occasionsdiscount",
            name="ocassions",
        ),
        migrations.RemoveField(
            model_name="productdiscount",
            name="product",
        ),
        migrations.RemoveField(
            model_name="statusdiscount",
            name="status",
        ),
        migrations.RemoveField(
            model_name="stylesdiscount",
            name="style",
        ),
        migrations.RemoveField(
            model_name="subcategorydiscount",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="birthdaydiscount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="birthdaydiscount",
            name="valid_from",
            field=models.DateTimeField(default=make_aware(datetime(2025, 1, 1, 8, 30))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="birthdaydiscount",
            name="valid_to",
            field=models.DateTimeField(default=make_aware(datetime(2025, 1, 1, 8, 30))),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="birthdaydiscount",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Знижка, %"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="personaldiscount",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Знижка, %"
            ),
        ),
        migrations.AlterField(
            model_name="personaldiscount",
            name="valid_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="personaldiscount",
            name="valid_to",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_to",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("seasonal", "Сезонна"),
                            ("birthday", "День народження"),
                            ("personal", "Персональна"),
                            ("manual", "Ручна"),
                            ("promo", "Промокод"),
                            ("category", "По категоріях"),
                            ("product", "На продукт"),
                            ("occasion", "З приводу"),
                            ("coupon", "Купон"),
                            ("material", "На матеріал"),
                            ("status", "На статус"),
                            ("gemstone", "На камінь"),
                            ("size", "На розмір"),
                            ("gender", "На стать"),
                            ("collection", "На колекцію"),
                            ("style", "На стиль"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("combine_with_others", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="product.categories"),
                ),
                (
                    "collections",
                    models.ManyToManyField(blank=True, to="product.collections"),
                ),
                (
                    "gemstones",
                    models.ManyToManyField(blank=True, to="product.gemstone"),
                ),
                ("genders", models.ManyToManyField(blank=True, to="product.gender")),
                (
                    "materials",
                    models.ManyToManyField(blank=True, to="product.material"),
                ),
                (
                    "occasions",
                    models.ManyToManyField(blank=True, to="product.occasion"),
                ),
                ("products", models.ManyToManyField(blank=True, to="product.product")),
                (
                    "sizes",
                    models.ManyToManyField(blank=True, to="product.ringsizeconversion"),
                ),
                ("styles", models.ManyToManyField(blank=True, to="product.styles")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discounts.discount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CategoryDiscount",
        ),
        migrations.DeleteModel(
            name="CollectionDiscount",
        ),
        migrations.DeleteModel(
            name="GemstoneDiscount",
        ),
        migrations.DeleteModel(
            name="MaterialDiscount",
        ),
        migrations.DeleteModel(
            name="OccasionsDiscount",
        ),
        migrations.DeleteModel(
            name="ProductDiscount",
        ),
        migrations.DeleteModel(
            name="StatusDiscount",
        ),
        migrations.DeleteModel(
            name="StylesDiscount",
        ),
        migrations.DeleteModel(
            name="SubcategoryDiscount",
        ),
    ]
