# Generated by Django 5.1.6 on 2025-04-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_remove_collectiondiscount_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='genders',
        ),
    ]
