# Generated by Django 5.1.6 on 2025-04-11 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_categorydiscount_collectiondiscount_gemstonediscount_and_more'),
        ('product', '0028_alter_productcertificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaydiscount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='birthdaydiscount',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='birthdaydiscount',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='discount',
            name='genders',
            field=models.ManyToManyField(blank=True, to='product.gender'),
        ),
        migrations.AlterField(
            model_name='birthdaydiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Знижка на день народження, %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Початок дії'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Кінець дії'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Персональна знижка, %'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Початок дії'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Кінець дії'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Початок дії'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Кінець дії'),
        ),
        migrations.DeleteModel(
            name='DiscountUsage',
        ),
    ]
