# Generated by Django 5.1.6 on 2025-04-14 04:30

import discounts.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_remove_birthdaydiscount_is_active_and_more'),
        ('product', '0028_alter_productcertificate_file'),
        ('users', '0005_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasondiscount',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='coupon',
            name='combine_with_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='combine_with_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='combine_with_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='birthdaydiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, verbose_name='Знижка на день народження, %'),
        ),
        migrations.AlterField(
            model_name='birthdaydiscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_discount', to='users.userprofile', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_account', to='users.userprofile', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='collectiondiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='users.userprofile', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='gemstonediscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='materialdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='occasionsdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Персональна знижка, %'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_discounts', to='users.userprofile', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=discounts.models.generate_unique_promo_code, max_length=20, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='seasondiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='statusdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='stylesdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.AlterField(
            model_name='subcategorydiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Знижка, %'),
        ),
        migrations.CreateModel(
            name='DiscountUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.promocode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
