# Generated by Django 5.1.6 on 2025-04-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_remove_seasondiscount_discount_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaydiscount',
            old_name='user',
            new_name='profile',
        ),
    ]
