# Generated by Django 5.1.6 on 2025-04-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_rename_user_birthdaydiscount_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusaccount',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='personaldiscount',
            old_name='user',
            new_name='profile',
        ),
    ]
