# Generated by Django 5.1.6 on 2025-04-17 13:11

import discounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0014_rename_user_bonusaccount_profile_and_more'),
        ('product', '0029_product_is_ukrainian_cashback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldiscount',
            options={'verbose_name': 'Персональна знижка', 'verbose_name_plural': 'Персональні знижки'},
        ),
        migrations.AddField(
            model_name='personaldiscount',
            name='applicable_subproducts',
            field=models.ManyToManyField(blank=True, related_name='personal_discounts', to='product.subproducts', verbose_name='Застосовується до субпродуктів'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дійсна з'),
        ),
        migrations.AlterField(
            model_name='personaldiscount',
            name='valid_to',
            field=models.DateTimeField(default=discounts.models.default_valid_to, verbose_name='Дійсна до'),
        ),
    ]
