# Generated by Django 5.1.6 on 2025-04-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_alter_personaldiscount_options_and_more'),
        ('users', '0012_alter_userprofile_messengers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdaydiscount',
            options={'verbose_name': 'Знижка на день народження', 'verbose_name_plural': 'Знижки на день народження'},
        ),
        migrations.AddField(
            model_name='birthdaydiscount',
            name='birthday_at_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження на момент створення'),
        ),
        migrations.AddField(
            model_name='birthdaydiscount',
            name='used_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік використання знижки'),
        ),
        migrations.AlterField(
            model_name='birthdaydiscount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_discounts', to='users.userprofile', verbose_name='Користувач'),
        ),
    ]
