# Generated by Django 5.1.6 on 2025-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_alter_birthdaydiscount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occasionsdiscount',
            old_name='ocassions',
            new_name='occasions',
        ),
    ]
