# Generated by Django 5.1.6 on 2025-06-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0017_rename_ocassions_occasionsdiscount_occasions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купони'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Знижка', 'verbose_name_plural': 'Знижки'},
        ),
        migrations.AlterModelOptions(
            name='discountusagehistory',
            options={'ordering': ['-used_at'], 'verbose_name': 'Історія використання знижки', 'verbose_name_plural': 'Історії використання знижок'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо код', 'verbose_name_plural': 'Промо коди'},
        ),
    ]
