events {
    worker_connections 1024;
}

# The main HTTP context
http {
    # Include general configuration
    include       mime.types;
    default_type  application/octet-stream;

    # Logging settings (optional)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream web {
      server web:8000; # or the port your web service is listening on
    }

    # Server block for serving static and media files
    server {
        listen 8080;
        server_name localhost;

        # Serve static files
        location /static/ {
            alias /staticfiles/;  # The path where static files are stored in the container
        }

        # Serve media files
        location /media/ {
            alias /mediafiles/;  # Replace this with your media files directory if any
        }

        # Proxy all other requests to Gunicorn
        location / {
            proxy_pass http://web; # 'web' is the name of your Django (Gunicorn) container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
