# Generated by Django 5.1.6 on 2025-02-13 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +380123456789)', regex='^\\+\\d{1,15}$')]),
        ),
    ]
