# Generated by Django 5.1.7 on 2025-03-29 00:56

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=utils.multi_backend_image_field.MultiBackendImageField(
                blank=True, null=True, upload_to="avatars/"
            ),
        ),
    ]
