# Generated by Django 5.1.7 on 2025-03-30 18:15

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=utils.multi_backend_image_field.MultiBackendImageField(
                blank=True, max_length=255, null=True, upload_to="avatars/"
            ),
        ),
    ]
