# Generated by Django 5.1.6 on 2025-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='viber',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messengers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
