# Generated by Django 5.1.6 on 2025-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_telegram_remove_userprofile_viber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='messengers',
            field=models.JSONField(blank=True, db_column='messengers', default=dict),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='messengers',
            new_name='_messengers',
        ),
    ]
