# Generated by Django 5.1.6 on 2025-05-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_messengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ocassions_date',
            new_name='occassions_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ocassions_personal',
            new_name='occassions_personal',
        ),
    ]
