# Generated by Django 5.1.6 on 2025-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_ocassions_date_userprofile_occassions_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='occassions_date',
            new_name='occasions_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='occassions_personal',
            new_name='occasions_personal',
        ),
    ]
