# Generated by Django 5.2.6 on 2025-09-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_rename_occassions_date_userprofile_occasions_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("U", "Undefined")],
                max_length=1,
                null=True,
            ),
        ),
    ]
