# Generated by Django 5.1.6 on 2025-04-18 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_created_timestamp_alter_cart_quantity_and_more'),
        ('product', '0029_product_is_ukrainian_cashback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_key', 'product'), ('user', 'product')},
        ),
    ]
