"""
Django settings for project_1444 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import zoneinfo

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path
import os
from urllib.parse import urlparse

import environ
from datetime import timedelta

from pygments.lexer import default

from . import __version__

# from django.utils.translation import gettext_lazy as _

from django.conf.global_settings import STATIC_ROOT
import cloudinary
import cloudinary.uploader
import cloudinary.api
from cloudinary.utils import cloudinary_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default=None)
if not SECRET_KEY or SECRET_KEY.isspace():
    SECRET_KEY = "django-insecure-i&eu1qndfw3ooc#3@01b8)0(6z4yr(jfjh+=p1rk&@+j^o(m^i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False, cast=bool)
print(f"{DEBUG=}")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=None)

if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]

print(f"{ALLOWED_HOSTS=}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",
    "drf_spectacular",
    "djoser",
    "rest_framework.authtoken",
    "django_extensions",
    "parler",
    "cloudinary",
    "product",
    "users",
    "cart",
    "order",
    "warehouse",
    "discounts",
]
PARLER_LANGUAGES = {
    None: (
        {"code": "uk", "fallbacks": ["en"], "hide_untranslated": False},
        {"code": "en", "fallbacks": ["uk"], "hide_untranslated": False},
    ),
    "default": {
        "fallback": "uk",  # Яка мова буде за замовчуванням
    },
}
PARLER_LANGUAGES_LIST = [lang.get("code") for lang in PARLER_LANGUAGES.get(None, [])]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project_1444.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_1444.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

try:
    if not env("DATABASE_URL", default=None):
        raise environ.ImproperlyConfigured
    DATABASES = {"default": env.db()}
except environ.ImproperlyConfigured:
    try:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("DATABASE_NAME"),
                "USER": env("DATABASE_USER"),
                "PASSWORD": env("DATABASE_PASSWORD"),
                "HOST": env("DATABASE_HOST"),
                "PORT": env("DATABASE_PORT", default=5432),
            }
        }
    except environ.ImproperlyConfigured as e:
        print(
            "Database .env setting must have DATABASE_URL or set of DATABASE_HOST, DATABASE_NAME, DATABASE_USER, DATABASE_PASSWORD:",
            e,
        )
        raise ValueError(e)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# AUTH_USER_MODEL = 'users.User'
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "uk"

TIME_ZONE = "Europe/Kyiv"

USE_I18N = True

USE_TZ = True

# print([zone for zone in zoneinfo.available_timezones() if zone.startswith("Europe/K")])


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env("STATIC_URL", default="/static/")  # 'static/'

# for manage.py collect static
STATIC_ROOT = BASE_DIR / "static"
# for additional static files outside static_root
# STATICFILES_DIRS = [ BASE_DIR / 'static' ]
# print(f"static_dir: {STATICFILES_DIRS}")

# MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

try:
    try:
        CLOUDINARY_URL = env("CLOUDINARY_URL")
        cl_url = urlparse(CLOUDINARY_URL)
        if cl_url.scheme == "cloudinary":
            CLOUDINARY_NAME = cl_url.hostname
            CLOUDINARY_API_KEY = cl_url.username
            CLOUDINARY_API_SECRET = cl_url.password
            if not all([CLOUDINARY_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET]):
                raise ValueError
        else:
            raise ValueError
    except (ValueError, KeyError, environ.ImproperlyConfigured) as e:
        CLOUDINARY_NAME = env("CLOUDINARY_NAME")
        CLOUDINARY_API_KEY = env("CLOUDINARY_API_KEY")
        CLOUDINARY_API_SECRET = env("CLOUDINARY_API_SECRET")

    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_URL = f"https://res.cloudinary.com/{CLOUDINARY_NAME}/image/upload/"
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
        "SECURE": True,  # Додає https
    }
except (KeyError, environ.ImproperlyConfigured) as e:
    print(
        "CLOUDINARY not configured correctly by environs. Can setup CLOUDINARY_URL, or their components.  Error:",
        str(e),
    )


# MEDIA_URL = env("CLOUDINARY_URL")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

try:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST")
    EMAIL_PORT = env("EMAIL_PORT", cast=int, default=465)
    EMAIL_USE_SSL = env("EMAIL_USE_SSL", cast=bool, default=True)
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    if not EMAIL_HOST:
        EMAIL_BACKEND = None
except (KeyError, environ.ImproperlyConfigured):
    EMAIL_BACKEND = None


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL", default=None
)  # Redis як брокер повідомлень
if not CELERY_BROKER_URL:
    CELERY_BROKER_URL = "redis://localhost:6379/0"

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND", default=None
)  # Redis як брокер повідомлень
if not CELERY_RESULT_BACKEND:
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL or "redis://localhost:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = not CORS_ALLOWED_ORIGINS

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

GIT_VERSION = env("GIT_VERSION", default="Version is unknown")
VERSION = env("VERSION", default=__version__)
CACHE_HEADERS_ENABLED = env("CACHE_HEADERS_ENABLED", default=False, cast=bool)


# print(f"{CORS_ALLOWED_ORIGINS=}, {CORS_ALLOW_ALL_ORIGINS=}, {CSRF_TRUSTED_ORIGINS=}")
