@echo off
PUSHD ".."
echo .
echo Starting Docker web only
if not exist .env-docker (
    echo Creating .env-docker...
    echo # This file was generated by run_docker_web.cmd > .env-docker
    echo DEBUG=True > .env-docker
) else (
    echo .env-docker already exists.
)
docker compose --env-file .env-docker up --build
POPD
