# Generated by Django 5.1.7 on 2025-03-19 08:10

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_length', models.BooleanField(default=False, verbose_name='Має довжину (см)')),
                ('has_width', models.BooleanField(default=False, verbose_name='Має ширину (см)')),
                ('has_diameter', models.BooleanField(default=False, verbose_name='Має діаметр (мм)')),
                ('has_weight', models.BooleanField(default=True, verbose_name='Має вагу (г)')),
            ],
            options={
                'verbose_name': 'Категорія виробу',
                'verbose_name_plural': 'Категорії виробів',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('precious', 'Precious'), ('semi-precious', 'Semi-Precious'), ('nonprecious', 'NonPrecious')], max_length=20, null=True)),
                ('origin_stone', models.CharField(blank=True, choices=[('natural', 'Natural'), ('synthetic', 'Synthetic')], max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('precious_1', 'Precious I Order'), ('precious_2', 'Precious II Order'), ('precious_3', 'Precious III Order'), ('precious_4', 'Precious IV Order'), ('semi_precious_1', 'Semi-Precious I Order'), ('semi_precious_2', 'Semi-Precious II Order')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ювелірний камінь',
                'verbose_name_plural': 'Ювелірне каміння',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('female', 'Жіноче'), ('male', 'Чоловіче'), ('children', 'Дитяче'), ('unisex', 'Унісекс')], max_length=20)),
            ],
            options={
                'verbose_name': 'Для кого',
                'verbose_name_plural': 'Для кого',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('gold', 'Золото'), ('silver', 'Срібло'), ('platinum', 'Платина'), ('steel', 'Сталь')], max_length=50, null=True)),
                ('assay', models.CharField(blank=True, choices=[('0', '0'), ('585', '585'), ('750', '750'), ('925', '925'), ('950', '950')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'Білий'), ('yellow', 'Жовтий'), ('red', 'Червоний'), ('brown', 'Коричневий'), ('rhodium_plating', 'Родіювання'), ('black', 'Чорний'), ('blackening', 'Чорніння')], max_length=50, null=True)),
                ('article', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Привід',
                'verbose_name_plural': 'Приводи',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RingSizeConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circumference_mm', models.FloatField(unique=True)),
                ('diameter_mm', models.FloatField()),
                ('size_ua', models.CharField(max_length=10)),
                ('size_us', models.CharField(blank=True, max_length=10, null=True)),
                ('size_eu', models.CharField(blank=True, max_length=10, null=True)),
                ('size_uk', models.CharField(blank=True, max_length=10, null=True)),
                ('size_asia', models.CharField(blank=True, max_length=10, null=True)),
                ('size_other_eu', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Конвертація розмірів',
                'verbose_name_plural': 'Конвертер розмірів',
            },
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('has_length', models.BooleanField(default=False)),
                ('has_width', models.BooleanField(default=False)),
                ('has_diameter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ean_13', models.CharField(blank=True, max_length=13, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('year_collection', models.IntegerField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categories')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.collections')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('occasions', models.ManyToManyField(blank=True, to='product.occasion')),
                ('size_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizetype')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Жіноче'), ('male', 'Чоловіче'), ('children', 'Дитяче'), ('unisex', 'Унісекс')], default='unisex', max_length=20, verbose_name='Gender')),
                ('color_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colors')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
                ('statuses', models.ManyToManyField(blank=True, related_name='products', to='product.productstatus')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='product.product')),
            ],
            options={
                'verbose_name': 'Сертифікат продукції',
                'verbose_name_plural': 'Сертифікати продукцій',
            },
        ),
        migrations.CreateModel(
            name='ProductGemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('set_included', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colors')),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.gemstone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemstones', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'gemstone', 'color')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Фото продукції',
                'verbose_name_plural': 'Фото продукцій',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='size_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizetype'),
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.categories')),
            ],
            options={
                'verbose_name': 'Підкатегорія виробу',
                'verbose_name_plural': 'Підкатегорії виробів',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategories'),
        ),
        migrations.CreateModel(
            name='SubProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ean_13', models.CharField(blank=True, max_length=13, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Довжина (см)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Ширина (см)')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='Діаметр (мм)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вага (г)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subproducts',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='product.subproducts'),
        ),
        migrations.CreateModel(
            name='CategoriesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Categories')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.categories')),
            ],
            options={
                'verbose_name': 'Категорія виробу Translation',
                'db_table': 'product_categories_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Collections')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.collections')),
            ],
            options={
                'verbose_name': 'Колекція Translation',
                'db_table': 'product_collections_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Colors')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.colors')),
            ],
            options={
                'verbose_name': 'Колір Translation',
                'db_table': 'product_colors_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GemstoneTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.gemstone')),
            ],
            options={
                'verbose_name': 'Ювелірний камінь Translation',
                'db_table': 'product_gemstone_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.material')),
            ],
            options={
                'verbose_name': 'Матеріал Translation',
                'db_table': 'product_material_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OccasionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.occasion')),
            ],
            options={
                'verbose_name': 'Привід Translation',
                'db_table': 'product_occasion_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttributesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('clasp_type', models.CharField(blank=True, max_length=255, null=True)),
                ('coating_material', models.CharField(blank=True, max_length=255, null=True)),
                ('description_coating', models.CharField(blank=True, max_length=255, null=True)),
                ('design_product', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productattributes')),
            ],
            options={
                'verbose_name': 'product attributes Translation',
                'db_table': 'product_productattributes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductGemstoneTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productgemstone')),
            ],
            options={
                'verbose_name': 'product gemstone Translation',
                'db_table': 'product_productgemstone_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('set_included', models.BooleanField(default=False)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productstatus')),
            ],
            options={
                'verbose_name': 'product status Translation',
                'db_table': 'product_productstatus_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description_product', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'product_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubCategoriesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.subcategories')),
            ],
            options={
                'verbose_name': 'Підкатегорія виробу Translation',
                'db_table': 'product_subcategories_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
