# Generated by Django 5.1.7 on 2025-03-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productattributes_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='size_type',
        ),
        migrations.DeleteModel(
            name='SizeType',
        ),
    ]
