# Generated by Django 5.1.6 on 2025-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasiontranslation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
