# Generated by Django 5.1.5 on 2025-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_material_assay_alter_material_metal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desccription_gemstone_main',
            new_name='color_gemstone_main',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desccription_gemstone_second',
            new_name='description_gemstone_main',
        ),
        migrations.AddField(
            model_name='product',
            name='description_gemstone_second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='assay',
            field=models.CharField(blank=True, choices=[('0', '0'), ('585', '585'), ('750', '750'), ('925', '925'), ('950', '950')], max_length=20, null=True),
        ),
    ]
