# Generated by Django 5.1.6 on 2025-02-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_occasiontranslation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoriestranslation',
            name='parent',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.categories'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(blank=True, choices=[('gold', 'Золото'), ('silver', 'Срібло'), ('platinum', 'Платина'), ('steel', 'Сталь')], max_length=50, null=True),
        ),
    ]
