# Generated by Django 5.1.7 on 2025-03-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_size_type_remove_categories_size_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproducts',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='subproducts',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Розмір(мм) '),
        ),
    ]
