# Generated by Django 5.1.7 on 2025-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subproducts_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproducts',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вага (г)'),
        ),
    ]
