# Generated by Django 5.1.7 on 2025-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
