# Generated by Django 5.1.7 on 2025-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_subproducts_parent_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
    ]
