# Generated by Django 5.1.6 on 2025-02-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_subcategoriestranslation_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtranslation',
            name='type',
        ),
    ]
