# Generated by Django 5.1.5 on 2025-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_dimenstions_product_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('female', 'Жіноче'), ('male', 'Чоловіче'), ('children', 'Дитяче'), ('unisex', 'Унісекс')], max_length=20)),
            ],
            options={
                'verbose_name': 'Для кого',
                'verbose_name_plural': 'Для кого',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Привід',
                'verbose_name_plural': 'Приводи',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Жіноче'), ('male', 'Чоловіче'), ('children', 'Дитяче'), ('unisex', 'Унісекс')], default='unisex', max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, null=True, to='product.occasion'),
        ),
    ]
