# Generated by Django 5.1.7 on 2025-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_subproducts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='status', to='product.productstatus'),
        ),
    ]
