# Generated by Django 5.1.6 on 2025-02-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_materialtranslation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialTranslation',
        ),
    ]
