# Generated by Django 5.1.6 on 2025-02-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_gender_options'),
        ('product', '0006_alter_product_occasions'),
    ]

    operations = [
    ]
