# Generated by Django 5.1.7 on 2025-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productattributes_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='statuses',
        ),
        migrations.AddField(
            model_name='product',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='status', to='product.productstatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, related_name='occasion', to='product.occasion'),
        ),
    ]
