# Generated by Django 5.1.7 on 2025-03-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productattributes_statuses_product_statuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatus',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.product'),
        ),
    ]
