# Generated by Django 5.1.6 on 2025-03-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='gemstone_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_with_gem', to='product.gemstone'),
        ),
    ]
