# Generated by Django 5.1.7 on 2025-03-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productstatus_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstatus',
            name='parent_product',
        ),
    ]
