# Generated by Django 5.1.6 on 2025-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_producttranslation_gemstone_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Жіноче'), ('male', 'Чоловіче'), ('children', 'Дитяче'), ('unisex', 'Унісекс')], default='unisex', max_length=20),
        ),
    ]
