# Generated by Django 5.1.6 on 2025-03-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_collections_collectionstranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.collections'),
        ),
    ]
