# Generated by Django 5.1.7 on 2025-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproducts',
            name='max_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. довжина (см)'),
        ),
    ]
