# Generated by Django 5.1.6 on 2025-03-30 08:04

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=utils.multi_backend_image_field.MultiBackendImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
