# Generated by Django 5.1.6 on 2025-03-30 09:42

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=utils.multi_backend_image_field.MultiBackendImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
