# Generated by Django 5.1.6 on 2025-03-02 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_colors_colorstranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemstonetranslation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattributestranslation',
            name='color_coating',
        ),
        migrations.RemoveField(
            model_name='productgemstonetranslation',
            name='color',
        ),
        migrations.AddField(
            model_name='gemstone',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colors'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='color_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colors'),
        ),
        migrations.AddField(
            model_name='productgemstone',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colors'),
        ),
    ]
