# Generated by Django 5.1.6 on 2025-03-27 13:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_subproducts_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcertificate',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
