# Generated by Django 5.1.6 on 2025-03-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_gemstonetranslation_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategories'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='description_gemstone_first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
