# Generated by Django 5.1.6 on 2025-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_gender_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], null=True),
        ),
    ]
