# Generated by Django 5.1.6 on 2025-03-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_gemstone_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='description_gemstone_first',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='description_gemstone_second',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='gemstone_first',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='gemstone_second',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='status',
        ),
        migrations.AddField(
            model_name='productattributestranslation',
            name='status',
            field=models.CharField(choices=[('bestseller', 'Bestseller'), ('new', 'New'), ('classic', 'Classic'), ('stock', 'Stock')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='productgemstonetranslation',
            name='description_gemstone_first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgemstonetranslation',
            name='description_gemstone_second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgemstonetranslation',
            name='gemstone_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_with_gem', to='product.gemstone'),
        ),
        migrations.AddField(
            model_name='productgemstonetranslation',
            name='gemstone_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_with_second_gem', to='product.gemstone'),
        ),
    ]
