# Generated by Django 5.1.6 on 2025-03-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_weaving_weavingtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='weaving_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.weaving'),
        ),
    ]
