# Generated by Django 5.1.6 on 2025-03-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productattributes_weaving_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgemstone',
            name='gemstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gemstone'),
        ),
    ]
