# Generated by Django 5.1.6 on 2025-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_producttranslation_description_gemstone_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='set_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_gemstone_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_gemstone_second',
        ),
        migrations.AddField(
            model_name='productgemstone',
            name='set_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productgemstone',
            name='weight_gemstone_main',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productgemstone',
            name='weight_gemstone_second',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
