# Generated by Django 5.1.6 on 2025-03-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productimage_image'),
        ('product', '0019_coating_styles_and_more'),
    ]

    operations = [
    ]
