# Generated by Django 5.1.6 on 2025-04-03 10:49

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_merge_20250331_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='productgemstonetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productgemstonetranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='description_product',
        ),
        migrations.AddField(
            model_name='product',
            name='description_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.descriptions'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.descriptions'),
        ),
        migrations.AddField(
            model_name='productgemstone',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.descriptions'),
        ),
        migrations.CreateModel(
            name='DescriptionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.descriptions')),
            ],
            options={
                'verbose_name': 'Description Translation',
                'db_table': 'product_descriptions_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='ProductAttributesTranslation',
        ),
        migrations.DeleteModel(
            name='ProductGemstoneTranslation',
        ),
    ]
