# Generated by Django 5.1.6 on 2025-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_descriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionstranslation',
            name='slug',
        ),
    ]
