# Generated by Django 5.1.6 on 2025-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_descriptionstranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionstranslation',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
