# Generated by Django 5.1.6 on 2025-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_descriptionstranslation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionstranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
