# Generated by Django 5.1.6 on 2025-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_descriptionstranslation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_product',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='description',
        ),
        migrations.AddField(
            model_name='descriptionstranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='descriptionstranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
