# Generated by Django 5.1.6 on 2025-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_product_description_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_product',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.descriptions'),
        ),
    ]
