# Generated by Django 5.1.6 on 2025-04-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_description_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_product',
            new_name='description',
        ),
    ]
