# Generated by Django 5.1.7 on 2025-04-07 23:11

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_rename_description_product_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcertificate",
            name="file",
            field=utils.multi_backend_image_field.MultiBackendImageField(
                blank=True, max_length=255, null=True, upload_to="file/"
            ),
        ),
    ]
