# Generated by Django 5.1.7 on 2025-04-08 02:15

# import cloudinary_storage.storage
import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0027_alter_productcertificate_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcertificate",
            name="file",
            field=utils.multi_backend_image_field.MultiBackendFileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="file/",
            ),
        ),
    ]
