# Generated by Django 5.1.6 on 2025-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productcertificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ukrainian_cashback',
            field=models.BooleanField(default=False),
        ),
    ]
