# Generated by Django 5.1.6 on 2025-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_is_ukrainian_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtranslation',
            name='color_name',
            field=models.CharField(default=2025, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialtranslation',
            name='material_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('yellow', 'yellow'), ('red', 'red'), ('brown', 'brown'), ('rhodium_plating', 'rhodium_plating'), ('black', 'black'), ('blackening', 'blackening')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(blank=True, choices=[('gold', 'gold'), ('silver', 'silver'), ('platinum', 'platinum'), ('steel', 'steel')], max_length=50, null=True),
        ),
    ]
