# Generated by Django 5.1.6 on 2025-06-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_materialtranslation_color_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasp',
            options={'verbose_name': 'Застібка', 'verbose_name_plural': 'Застібки'},
        ),
    ]
