# Generated by Django 5.1.6 on 2025-06-19 04:35

import utils.multi_backend_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_clasp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=utils.multi_backend_image_field.MultiBackendImageField(blank=True, max_length=500, null=True, upload_to='image/'),
        ),
    ]
