# Generated by Django 5.1.6 on 2025-09-09 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_alter_productimage_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subproducts",
            index=models.Index(fields=["price"], name="product_sub_price_50eecd_idx"),
        ),
    ]
