# Generated by Django 5.2.6 on 2025-10-09 11:13

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0033_subproducts_product_sub_price_50eecd_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gender",
            options={"verbose_name": "Для кого", "verbose_name_plural": "Для кого"},
        ),
        migrations.RemoveField(
            model_name="gender",
            name="name",
        ),
        migrations.AddField(
            model_name="gender",
            name="gender",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productattributes",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.gender",
                verbose_name="Gender",
            ),
        ),
        migrations.CreateModel(
            name="GenderTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("name", models.CharField(max_length=50, verbose_name="Назва гендеру")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="product.gender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Для кого Translation",
                "db_table": "product_gender_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
