# Generated by Django 5.2.6 on 2025-10-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0034_alter_gender_options_remove_gender_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gender",
            name="gender",
        ),
    ]
