
name: DEPLOY

permissions:
  contents: read
  pull-requests: write

# on:
#   workflow_run:
#     workflows: ["Django CI"]
#     types:
#       - completed

on:
  pull_request:
  push:
    branches: [ "deploy", "dev-lexxai-deploy" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        # Only run this step if the branch is main
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          deploy_static_url: ${{ secrets.RENDER_DEPLOY_HOOK_STATIC_URL }}
        run: |
          if [ -n "$deploy_url" ]; then
            echo "Deploying to $deploy_url"
            curl "$deploy_url"
          else
            echo "No deploy url found"
          fi
          if [ -n "deploy_static_url" ]; then
            echo "Deploying to deploy_static_url"
            curl "deploy_static_url"
          else
            echo "No deploy static url found"
          fi

